### ISSUE TITLE
Make Hugo work with Go 1.11 (and Go 1.10)

### ISSUE THREAD

**Issue by rjoleary** [gohugoio/hugo#4784]
I'm on the Go master branch, Ubuntu 16.04, Linux 4.4.0-127-generic:

```
% go version
go version devel +65c365b Wed May 23 23:51:30 2018 +0000 linux/amd64
```

The following (gotten from [getting started](https://gohugo.io/getting-started/installing#fetch-from-github)) runs as expected:

```
go get github.com/magefile/mage
go get -d github.com/gohugoio/hugo
cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
mage vendor
```

However, running install fails:

```
% mage install
# github.com/gohugoio/hugo/tpl/tplimpl
tpl/tplimpl/template_ast_transformers.go:116:18: cannot range over x.Decl (type bool)
tpl/tplimpl/template_ast_transformers.go:132:10: undefined: parse.VariableNode
tpl/tplimpl/template_ast_transformers.go:133:30: an.Ident undefined (type parse.Node has no field or method Ident)
Error: running "go install -ldflags -X github.com/gohugoio/hugo/hugolib.CommitHash=d68367c -X github.com/gohugoio/hugo/hugolib.BuildDate=2018-05-27T08:47:25-0400 github.com/gohugoio/hugo" failed with exit code 2
```

It appears hugo depends on "text/template/parse" which got an API change on [Dec 17](https://github.com/golang/go/commit/28c1ad9d35f27b3b57afff4ee78faac746a8ed0a#diff-e04f7a5dd779d944dd776f82dcf35268) which was merged to master in April:

```
To avoid confusion, rename PipeNode.Decl to PipeNode.Vars, as the
variables may not always be declared after this change.
```

Renaming `Decl` to `Vars` and `VariableNode` to `AssignNode` in "template_ast_transformers.go" allowed Hugo to install:

```
% hugo version
Hugo Static Site Generator v0.42-DEV-D68367C linux/amd64 BuildDate: 2018-05-27T09:03:03-0400
```

It seems out of the ordinary for Go to have a breaking change. It would be nice to be able to install hugo with Go master.

**Comment by bep** [comment]
Go's master branch is not supported. We will eventually fix this.

**Comment by anthonyfok** [comment]
Regarding the escaped `<nil>` output from html/template in Go tip (pre-Go1.11), i.e. golang/go#25875, upstream has come up with a proposed fix at https://go-review.googlesource.com/c/go/+/118835, pending review and discussion, with a disclaimer at the bottom of the commit message:

> DO NOT SUBMIT - we haven't yet decided if this is the right path forward.

Full diff of the proposed fix: https://go.googlesource.com/go/+/46c521a7ee4d04971a828d0c0f9d698e1641344d%5E%21/
