### ISSUE TITLE
Inconsistent build rules between Linux (debian and snap installs) and MacOS (brew install)

### ISSUE THREAD

**Issue by ndtreviv** [gohugoio/hugo#6067]
I have a site that builds just fine on MacOS, but when I attempt to build on Linux (Ubuntu 16.04LTS) I get a ton of errors:
```
ERROR: 2019/06/28 06:57:12 template.go:350: template: _default/list.html:31: function "i18n" not defined
ERROR: 2019/06/28 06:57:12 template.go:350: template: _default/single.html:31: function "fileExists" not defined
ERROR: 2019/06/28 06:57:12 template.go:350: template: partials/footer.html:28: function "now" not defined
ERROR: 2019/06/28 06:57:12 template.go:350: template: partials/nav.html:16: unexpected "=" in operand
ERROR: 2019/06/28 06:57:12 page.go:555: Failed to parse date '2016-06-24T1904-07:00' in page _index.md
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for about.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for contact.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for partners.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for login.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for terms.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:832: Error parsing page meta data for privacy.md
ERROR: 2019/06/28 06:57:12 page.go:833: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
ERROR: 2019/06/28 06:57:12 page.go:393: Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead.
Error: Error building site: Errors reading pages: Error:Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for about.md
Error:Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for contact.md
Error:Near line 4 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for partners.md
Error:Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for login.md
Error:Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for terms.md
Error:Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for privacy.md
```

Looking at the versions, there is a big difference:
Version on jenkins: `Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T17:14:17Z`
Version on OSX: `Hugo Static Site Generator v0.55.6/extended darwin/amd64 BuildDate: unknown`

Is that expected?
I tried installing hugo on Linux both using `apt-get install hugo`, and when I got the errors I `apt-get remove`-d it and installed via snap. Same problems, same version.

**Comment by ndtreviv** [comment]
It turns out that the versions installed by debian and snap were the wrong ones.
