### ISSUE TITLE
regression: Panic when user does not have write access to /tmp/hugo_cache

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9539]
Introduced with a2a660e. This is the third issue related to this commit; see also #9518 and #9530.

Ref: <https://discourse.gohugo.io/t/hugo-on-ubuntu-20-04-panic/37294/>

Silly example, but...

```text
drwxrwxr-x   5 games    games      4096 Feb 21 08:13 hugo_cache
```

The current user is not a member of the `games` group.

```bash
$ groups
jmooring adm cdrom sudo dip plugdev lpadmin lxd sambashare
```

Build the site with `hugo`.

> panic: runtime error: invalid memory address or nil pointer dereference

<details>

```text
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1c77b2c]

goroutine 1 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/home/jmooring/code/hugo/commands/commandeer.go:426 +0x58c
sync.(*Once).doSlow(0x2726ab0?, 0x2248b52?)
	/snap/go/current/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/snap/go/current/src/sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0003920f0)
	/home/jmooring/code/hugo/commands/commandeer.go:377 +0x8a6
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x0, 0xc0005a60e0, {0x27112c0?, 0xc0005a2050}, 0xc0005a24c0, {0x0, 0x0, 0x0})
	/home/jmooring/code/hugo/commands/commandeer.go:195 +0x310
github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0xfd?, 0x6b?, 0xc0006bfca0?, {0x27112c0?, 0xc0005a2050?}, 0x2d?)
	/home/jmooring/code/hugo/commands/hugo.go:126 +0x31
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc000572000, {0x21f1d56?, 0x0?, 0x0?})
	/home/jmooring/code/hugo/commands/commands.go:166 +0x135
github.com/spf13/cobra.(*Command).execute(0xc000572000, {0xc00003c200, 0x0, 0x0})
	/home/jmooring/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000572000)
	/home/jmooring/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/gohugoio/hugo/commands.Execute({0xc00003c200, 0x0, 0x0})
	/home/jmooring/code/hugo/commands/hugo.go:93 +0xb4
main.main()
	/home/jmooring/code/hugo/main.go:23 +0x57
```
</details>

**Comment by bep** [comment]
Just to be clear: All of these are error situations, right, which should produce error with a sensible message and not panic?

**Comment by jmooring** [comment]
> All of these are error situations, right, which should produce error with a sensible message and not panic?

Correct. Prior to a2a660e they produced sensible messages.

**Comment by bep** [comment]
>Prior to https://github.com/gohugoio/hugo/commit/a2a660ed1209528b075a21af84fc0ed3e7b266ef they produced sensible messages.

With a deadlock, so progress :-)
