### ISSUE TITLE
Index $.Site.Taxonomies does not work in Hugo 0.18.1

### ISSUE THREAD

**Issue by mikhail73** [gohugoio/hugo#2918]
`Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T10:03:28+03:00`

Details: https://discuss.gohugo.io/t/index-site-taxonomies-does-not-work-in-hugo-0-18/5076

I have done such a test:
```
{{ $test := (index $.Site.Taxonomies.authors .Title) }}
{{ printf "%S" $test }}
```

It generates `[]`
This is a template: \layouts\taxonomy\author.html

**Comment by mikhail73** [comment]
It does not work in any case `preservetaxonomynames:  true of false`

**Comment by bep** [comment]
What is the content of $.Site.Taxonomies.authors ?

**Comment by mikhail73** [comment]
http://andreeva.newgod.su/authors/

**Comment by mikhail73** [comment]
I think I solved the problem. Working code:
``
{{ $ltitle := (replaceRE "( |–)" "-" (lower .Title)) }}
{{ range (index $.Site.Taxonomies.authors $ltitle).Pages }}`
```

**Comment by eyedol** [comment]
Not sure if this is related but I'm facing similar issue.

This code was working with `v0.16` until I upgraded to `v0.18.1`
```go
{{ $contact := index $.Site.Menus.Main 5 }}
```

Error message 
```go
ERROR: 2017/01/16 10:39:45 general.go:236: Error while rendering "page ": template: index.html:3:15: executing "index.html" at <index $.Site.Menus.M...>: error calling index: index of untyped nil
```
Content of `$.Site.Menus.Main` is 
```goo
Menu:
    Main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
        - Name: "About Us"
          Weight: 1
          Identifier: "about"
          URL: "about"
        - Name: "Constitution"
          Weight: 2
          Identifier: "constitution"
          URL: "constitution"
        ...
```

If they're unrelated let me know. I'll open a different issue.

**Comment by eyedol** [comment]
It turns out from hugo `v0.17` this is how to declare menus. 
```go
menu:
    main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
        - Name: "About Us"
          Weight: 1
          Identifier: "about"
          URL: "about"
        - Name: "Constitution"
          Weight: 2
          Identifier: "constitution"
          URL: "constitution"
        ...
```

Otherwise `$.Site.Menus.Main` returns nil unless accessed as `.Site.Menus.main`
